### ISSUE TITLE
make command not working when trying to install the nvim nightly version

### ISSUE THREAD

**Issue by fontoful** [s1n7ax/archived-dotnvim#1]
Hey bud, 

so I'm following the steps outlined in your Readme and when I want to do make and sudo make install I get this error: 

cd .deps && \
	cmake -G 'Unix Makefiles'   \
	 /home/hector/neovim/third-party
/bin/sh: 2: cmake: not found
make: *** [Makefile:112: build/.ran-third-party-cmake] Error 127

I have already cloned your repo and settings but because my neovim version 5 failed to install, I think that's my roadblock. 

I'd appreciate any help. I tried updating my $PATH and some other workaround online but I've failed so far.

**Comment by mateusfdl** [comment]
It looks like you don't have dependencies installed, i recommend install it https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites

**Comment by s1n7ax** [comment]
Sorry for late reply. As suggested please check the build guide on neovim for more information. How ever I fixed the README to include `build-essential` and `cmake`. Please install those two packages to install tools required to build the project
