### ISSUE TITLE
Error running config for nvim-lsp-installer

### ISSUE THREAD

**Issue by anand58** [s1n7ax/archived-dotnvim#2]
I'm seeing the following error once I clone your dotnvim project and open nvim. 

packer.nvim: Error running config for nvim-lsp-installer: /home/anand/.config/nvim/lua/nvim/utils/lsp/config.lua:1: module 'pl.class' not found:
^Ino field package.preload['pl.class']
^Ino file './pl/class.lua'
^Ino file '/usr/share/luajit-2.1.0-beta3/pl/class.lua'
^Ino file '/usr/local/share/lua/5.1/pl/class.lua'
^Ino file '/usr/local/share/lua/5.1/pl/class/init.lua'
^Ino file '/usr/share/lua/5.1/pl/class.lua'
^Ino file '/usr/share/lua/5.1/pl/class/init.lua'
^Ino file '/home/anand/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/pl/class.lua'
^Ino file '/home/anand/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/pl/class/init.lua'
^Ino file '/home/anand/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/pl/class.lua'
^Ino file '/home/anand/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/pl/class/init.lua'
^Ino file './pl/class.so'
^Ino file '/usr/local/lib/lua/5.1/pl/class.so'
^Ino file '/usr/lib/x86_64-linux-gnu/lua/5.1/pl/class.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/home/anand/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/pl/class.so'
^Ino file './pl.so'
^Ino file '/usr/local/lib/lua/5.1/pl.so'
^Ino file '/usr/lib/x86_64-linux-gnu/lua/5.1/pl.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

Can you update the repo with the latest stable code?

**Comment by s1n7ax** [comment]
main branch up to date. There is a dependency to `penlight lua` module. Seems it is not installed when you run `:PackerInstall`. May I know what OS you have? You can try installing `luarocks` directly in the operation system and run `:PackerSync` after.

**Comment by anand58** [comment]
I'm using Ubuntu. When I'm doing :PackerSync, luarocks-hererocks isnt getting installed. Then I keep getting the above error every time I try to bring up nvim

Edit: More specifically the above error comes when I do :PackerCompile

**Comment by s1n7ax** [comment]
For luarocks-hererocks you need python3. Give me one day I will update the details after trying this on Ubuntu.

**Comment by anand58** [comment]
Thanks. That will be helpful

**Comment by s1n7ax** [comment]
I found the reason why `hererocks` is not installed. On `Ubuntu` you need to install `python-is-python3` so you can run `python` to use `python3`. `luarocks` is not necessary apparently.

I created a [script to install](https://github.com/s1n7ax/dotnvim/blob/main/scripts/setup-conf-ubuntu.sh) 70% stuff required to use my config on `Ubuntu 20.04` minimal version. I suck at bash so if there are conflicts those scenarios are not handled and probably won't work.

For java debugging you need to place following jars to `~/.local/share/nvim/lsp_servers/jdtls/additional-plugins/` (create the additional-plugins directory)
[com.microsoft.java.debug.plugin_0.33.0.jar](https://repo1.maven.org/maven2/com/microsoft/java/com.microsoft.java.debug.plugin/0.33.0/)
[com.microsoft.java.test.plugin-0.32.0.jar](https://github.com/microsoft/vscode-java-test)

`com.microsoft.java.test.plugin` jar is not available in maven so you will have to follow the instruction in the repo to get the jar.

**Comment by anand58** [comment]
Thanks a ton man. I'll try out these steps and let you know.

**Comment by anand58** [comment]
> I found the reason why `hererocks` is not installed. On `Ubuntu` you need to install `python-is-python3` so you can run `python` to use `python3`. `luarocks` is not necessary apparently.
> 
> I created a [script to install](https://github.com/s1n7ax/dotnvim/blob/main/scripts/setup-conf-ubuntu.sh) 70% stuff required to use my config on `Ubuntu 20.04` minimal version. I suck at bash so if there are conflicts those scenarios are not handled and probably won't work.
> 
> For java debugging you need to place following jars to `~/.local/share/nvim/lsp_servers/jdtls/additional-plugins/` (create the additional-plugins directory) [com.microsoft.java.debug.plugin_0.33.0.jar](https://repo1.maven.org/maven2/com/microsoft/java/com.microsoft.java.debug.plugin/0.33.0/) [com.microsoft.java.test.plugin-0.32.0.jar](https://github.com/microsoft/vscode-java-test)
> 
> `com.microsoft.java.test.plugin` jar is not available in maven so you will have to follow the instruction in the repo to get the jar.

I cant access the install script that you have mentioned above
